### ISSUE TITLE
uninitialized constant Sidekiq::Worker (NameError)

### ISSUE THREAD

**Issue by paladini** [andersondias/sidekiq_mailer#17]
Hello guys,

Today I discovered this wonderful gem, this really can help my project. But I'm having some issues in installation/configuration, someone can help me?

Currently I'm using the lastest version of Sidekiq and the lastest version of SidekiqMailer. Following you can check my gemfile:

``` ruby
gem 'sidekiq'
gem "sidekiq-cron" 
gem 'sidekiq-failures' 
gem 'sidekiq_mailer', git: 'https://github.com/andersondias/sidekiq_mailer.git'
```

I'm using all this gems, but in different purposes / features. I have two workers at the moment: one that uses "sidekiq" + "sidekiq-cron" and another (I think you have a good guess) that uses "sidekiq" + "sidekiq_mailer". 

I have one **PersonMailer**, but this don't use "sidekiq_mailer" yet:

``` ruby
class PersonMailer < ActionMailer::Base

  default from: "no-reply@myAwesomeProject.com"

  # Templates in "views/mailers/mailer_name/method_name.html.erb"
  default template_path: "mailers/#{self.name.underscore}"

  def send_email_new_user(user)
    @user = user
    mail(to: @user.email, subject: "You = <3")
  end

end
```

And I call my mailer this way (inside PersonController):

``` ruby
PersonMailer.send_email_new_user(user).deliver
```

Now let's talk about my error. After I run `bundle install` in Terminal, I can't start my localhost server (`rails s`). Always I try it I receive the following error:

``` ruby
/home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/bundler/gems/sidekiq_mailer-4a5881b10c2a/lib/sidekiq_mailer/worker.rb:2:in `<class:Worker>': uninitialized constant Sidekiq::Worker (NameError)
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/bundler/gems/sidekiq_mailer-4a5881b10c2a/lib/sidekiq_mailer/worker.rb:1:in `<top (required)>'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/bundler/gems/sidekiq_mailer-4a5881b10c2a/lib/sidekiq_mailer.rb:2:in `<top (required)>'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:76:in `require'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in `each'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in `block in require'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in `each'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in `require'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/bundler-1.6.5/lib/bundler.rb:132:in `require'
    from /home/paladini/Documents/Programacao/myAwesomeProject/config/application.rb:6:in `<top (required)>'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/railties-3.2.3/lib/rails/commands.rb:53:in `require'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/railties-3.2.3/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
    from /home/paladini/.rvm/gems/ruby-1.9.3-p547@myAwesomeProject/gems/railties-3.2.3/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by andersondias** [comment]
Can you remove sidekiq-cron and sidekiq-failures gems, and test if it works?

**Comment by paladini** [comment]
Oh, sorry, but I'm not using sidekiq_mailer anymore. I didn't receive any answer and can't solve the problem by myself, so that I give up using `sidekiq_mailer`. If I come back to this gem, find this problem again and find a solution, I'll come here to post the found solution. 

Anyway, thanks! :)

**Comment by sriharshakappala** [comment]
Facing same issue, what might be the reason?
